import {useEffect,useRef,useState} from 'react';
import {acquireBodyScrollLock} from './bodyScrollLock.js';
import {blogFields,koreaToday,shiftDate,rankLabel,latestRank,rankDelta,sortBlog} from './blogModel.js';
import './blogStatus.css';

function Modal({title,onClose,children,busy=false}){const ref=useRef();useEffect(()=>{const before=document.activeElement,unlock=acquireBodyScrollLock();ref.current?.querySelector('input,button')?.focus();return()=>{unlock();before?.focus();};},[]);return <div className="blog-modal-bg" onClick={e=>{if(e.target===e.currentTarget&&!busy)onClose();}}><section ref={ref} role="dialog" aria-modal="true" aria-label={title} onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.stopPropagation();onClose();}if(e.key==='Tab'){const all=[...ref.current.querySelectorAll('button,input,select,a[href]')].filter(x=>!x.disabled);if(e.shiftKey&&document.activeElement===all[0]){e.preventDefault();all.at(-1)?.focus();}else if(!e.shiftKey&&document.activeElement===all.at(-1)){e.preventDefault();all[0]?.focus();}}}}><header><h3>{title}</h3><button disabled={busy} onClick={onClose} aria-label="닫기">✕</button></header>{children}</section></div>;}
function Editor({item,platform,onClose,onSave}){const [fields,set]=useState(()=>({...item,id:item?.id||crypto.randomUUID(),platform,title:item?.title||'',url:item?.url||'',keyword:item?.keyword||'',published_on:item?.published_on||koreaToday(),monthly_volume:item?.monthly_volume??'',goal_rank:item?.goal_rank||5}));const [busy,lock]=useState(false),[error,fail]=useState('');const dirty=useRef(false),saving=useRef(false);const close=()=>{if(!busy&&(!dirty.current||window.confirm('작성 중인 내용을 버릴까요?')))onClose();};return <Modal title={item?'포스팅 수정':'포스팅 등록'} busy={busy} onClose={close}><form onSubmit={async e=>{e.preventDefault();if(saving.current)return;saving.current=true;lock(true);fail('');try{await onSave(blogFields(fields));onClose();}catch(err){fail(err.message);}finally{saving.current=false;lock(false);}}}><p>{platform==='NAVER'?'네이버':'구글'} · 한 URL에 여러 목표 키워드를 각각 등록할 수 있습니다.</p><fieldset disabled={busy}>{[['title','포스팅 제목','text'],['url','게시물 URL','url'],['keyword','목표 키워드','text'],['published_on','게시일 / 예정일','date'],['monthly_volume','월 검색량 · 수동 입력','number'],['goal_rank','목표 순위','number']].map(([key,label,type])=><label key={key}>{label}{!['monthly_volume'].includes(key)&&<small>필수</small>}<input name={key} type={type} required={key!=='monthly_volume'} min={type==='number'?key==='goal_rank'?1:0:undefined} max={key==='goal_rank'?100:key==='monthly_volume'?2147483647:undefined} maxLength={key==='title'?300:key==='keyword'?100:key==='url'?2000:undefined} step={type==='number'?1:undefined} value={fields[key]} onChange={e=>{dirty.current=true;set({...fields,[key]:e.target.value});}}/></label>)}</fieldset>{error&&<p role="alert" className="blog-error">{error}</p>}<footer><button type="button" disabled={busy} onClick={close}>취소</button><button className="blog-primary" disabled={busy}>{busy?'저장 중…':'저장'}</button></footer></form></Modal>;}
function Volume({item,onSave}){
 const [value,set]=useState(item.monthly_volume??''),[busy,lock]=useState(false),[error,fail]=useState('');
 useEffect(()=>set(item.monthly_volume??''),[item.monthly_volume]);
 const commit=async e=>{if(String(value)===String(item.monthly_volume??''))return;if(!e.target.checkValidity()){fail('정수 입력');return;}lock(true);fail('');try{await onSave(value===''?null:Number(value));}catch(err){fail(err.message);}finally{lock(false);}};
 return <><input className="blog-volume" aria-label={item.keyword+' 월 검색량'} type="number" min="0" max="2147483647" step="1" placeholder="입력" value={value} disabled={busy} onChange={e=>set(e.target.value)} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/>{busy&&<small>저장 중</small>}{error&&<small role="alert" className="blog-error">{error}</small>}</>;
}
function Detail({item,history,onClose,onSave,canWrite}){const [date,setDate]=useState(koreaToday()),[state,setState]=useState('RANKED'),[rank,setRank]=useState(''),[busy,lock]=useState(false),[error,fail]=useState('');const existing=history.find(r=>r.target_id===item.id&&r.recorded_on===date);useEffect(()=>{setState(existing?.state||'RANKED');setRank(existing?.rank??'');},[date,existing]);return <Modal title={item.title} busy={busy} onClose={onClose}><p>{item.keyword} · 수동 기록 / 자동 수집 미연결</p><a href={item.url} target="_blank" rel="noopener noreferrer">게시물 열기 ↗</a>{canWrite&&<form onSubmit={async e=>{e.preventDefault();if(busy)return;lock(true);fail('');try{await onSave(existing,{recorded_on:date,state,rank});}catch(err){fail(err.message);}finally{lock(false);}}}><fieldset disabled={busy} className="blog-rank-form"><label>기록일<input type="date" required max={koreaToday()} value={date} onChange={e=>setDate(e.target.value)}/></label><label>측정 상태<select value={state} onChange={e=>setState(e.target.value)}><option value="RANKED">순위 확인</option><option value="OUT">100위 밖</option><option value="ERROR">측정 실패</option></select></label>{state==='RANKED'&&<label>순위<input type="number" min="1" max="100" step="1" required value={rank} onChange={e=>setRank(e.target.value)}/></label>}<button className="blog-primary">{busy?'저장 중…':existing?'기록 수정':'순위 기록'}</button></fieldset>{error&&<p role="alert" className="blog-error">{error}</p>}</form>}<h4>선택 기간의 기록</h4><div className="blog-history">{history.filter(r=>r.target_id===item.id).sort((a,b)=>b.recorded_on.localeCompare(a.recorded_on)).map(r=><div key={r.id}><span>{r.recorded_on} · 수동 입력</span><strong>{rankLabel(r)}</strong></div>)}{!history.some(r=>r.target_id===item.id)&&<p>기록이 없습니다. 날짜별 순위는 입력한 값만 표시합니다.</p>}</div></Modal>;}
export default function BlogStatusView({project,source,canWrite}){
 const [platform,setPlatform]=useState('NAVER'),[tab,setTab]=useState('rank'),[days,setDays]=useState(7),[end,setEnd]=useState(koreaToday()),[page,setPage]=useState(0),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[sort,setSort]=useState({key:'published_on',direction:-1}),[resource,setResource]=useState({status:'loading',items:[],history:[]}),[revision,refresh]=useState(0),[editor,setEditor]=useState(null),[detail,setDetail]=useState(null),[notice,setNotice]=useState('');
 const epoch=useRef(0);const from=shiftDate(end,1-days),context=project.id+platform+from+end+page;
 useEffect(()=>{const timer=setInterval(()=>{if(document.visibilityState==='visible'&&!document.querySelector('[role="dialog"]')&&!document.activeElement?.matches('input,select,textarea'))refresh(x=>x+1);},60000);return()=>clearInterval(timer);},[]);
 useEffect(()=>{const controller=new AbortController(),token=++epoch.current;setResource({status:'loading',items:[],history:[]});source.blog({projectId:project.id,platform,from,to:end,page,signal:controller.signal}).then(result=>{if(token===epoch.current&&!controller.signal.aborted)setResource({status:'ready',...result.data});}).catch(e=>{if(!controller.signal.aborted&&token===epoch.current)setResource({status:'error',items:[],history:[],error:e.message});});return()=>{controller.abort();epoch.current++;};},[source,context,revision]);
 const {items=[],history=[]}=resource;const rows=sortBlog(items.filter(r=>(r.title+' '+r.keyword).toLowerCase().includes(query.toLowerCase())).filter(r=>filter==='all'||filter==='goal'&&(latestRank(r,history)?.state==='RANKED'&&latestRank(r,history).rank<=r.goal_rank)||filter==='drop'&&rankDelta(r,history)<0||filter==='unmeasured'&&!latestRank(r,history)),history,sort.key,sort.direction);
 const dates=Array.from({length:days},(_,i)=>shiftDate(from,i));const header=(label,key)=><th aria-sort={sort.key===key?(sort.direction===1?'ascending':'descending'):'none'}><button onClick={()=>setSort({key,direction:sort.key===key?-sort.direction:1})}>{label} <span>{sort.key===key?(sort.direction===1?'↑':'↓'):'↕'}</span></button></th>;
 const save=async(item,fields)=>{const token=epoch.current;const result=await source.saveBlog({projectId:project.id,item,fields});if(token===epoch.current){setResource(r=>({...r,items:item?r.items.map(x=>x.id===item.id?result.data:x):[result.data,...r.items]}));setNotice('저장되었습니다.');}return result;};
 return <div className="blog-view"><div className="blog-platform" role="tablist" aria-label="검색 플랫폼">{['NAVER','GOOGLE'].map(p=><button role="tab" aria-selected={platform===p} key={p} onClick={()=>{setPlatform(p);setPage(0);setDetail(null);setEditor(null);setNotice('');}}><b className={p.toLowerCase()}>{p==='NAVER'?'N':'G'}</b>{p==='NAVER'?'네이버':'구글'}</button>)}</div><div className="blog-heading"><div><h2>블로그 현황</h2><p>{project.clientName||project.name} · 게시 현황과 목표 키워드별 순위 기록</p></div>{canWrite&&<button className="blog-primary" onClick={()=>setEditor({})}>＋ 포스팅 등록</button>}</div><p className="blog-source">수동 관리 · 검색량 / 순위 자동 연동 없음 · 순위 출처: 담당자 입력</p><div className="blog-stats"><span>등록 포스팅 <b>{new Set(items.map(r=>r.url)).size}</b></span><span>목표 키워드 <b>{items.length}</b></span><span>목표 달성 <b>{items.filter(r=>latestRank(r,history)?.state==='RANKED'&&latestRank(r,history).rank<=r.goal_rank).length}</b></span><span>미측정 <b>{items.filter(r=>!latestRank(r,history)).length}</b></span><small>현재 페이지 · 선택 기간 기준</small></div><div className="blog-tabs">{[['rank','순위 추적'],['posts','게시 현황']].map(([key,label])=><button key={key} aria-pressed={tab===key} onClick={()=>setTab(key)}>{label}</button>)}</div><div className="blog-filters"><input aria-label="포스팅·목표 키워드 검색" placeholder="제목 · 목표 키워드 검색" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="순위 필터" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">전체 상태</option><option value="goal">목표 달성</option><option value="drop">순위 하락</option><option value="unmeasured">미측정</option></select><div className="blog-period">{[7,14,30].map(n=><button key={n} aria-pressed={days===n} onClick={()=>setDays(n)}>{n}일</button>)}<button aria-label="이전 기간" onClick={()=>setEnd(shiftDate(end,-days))}>‹</button><span>{from.slice(5)} — {end.slice(5)}</span><button aria-label="다음 기간" disabled={end>=koreaToday()} onClick={()=>setEnd(shiftDate(end,days)>koreaToday()?koreaToday():shiftDate(end,days))}>›</button></div></div><div role="status" className="blog-notice">{notice}</div>
 {resource.status==='loading'?<p role="status">블로그 현황을 불러오는 중입니다…</p>:resource.status==='error'?<div role="alert" className="blog-error">{resource.error}<button onClick={()=>refresh(x=>x+1)}>다시 시도</button></div>:<><div className="blog-table-scroll"><table><thead><tr>{header('포스팅 · 게시일','published_on')}{header('목표 키워드','keyword')}{header('월 검색량','monthly_volume')}{header('최근 순위','rank')}<th>전일 대비</th>{tab==='rank'?dates.map(d=><th key={d} className={d===koreaToday()?'blog-today':''}>{d.slice(5).replace('-','/')}</th>):<><th>게시 상태</th><th>게시물 링크</th></>}{canWrite&&<th>관리</th>}</tr></thead><tbody>{rows.map(item=>{const last=latestRank(item,history),delta=rankDelta(item,history);return <tr key={item.id}><td className="blog-title"><a href={item.url} target="_blank" rel="noopener noreferrer" title="게시글 새 탭에서 열기">{item.title} ↗</a><small>{item.published_on} · {item.platform==='NAVER'?'네이버':'구글'}</small></td><td>{item.keyword}<small>목표 {item.goal_rank}위 이내</small></td><td>{canWrite?<Volume item={item} onSave={monthly_volume=>save(item,{monthly_volume})}/>:item.monthly_volume??'—'}</td><td><button className="blog-rank-open" onClick={()=>setDetail(item)} aria-label={item.title+' 순위 기록 열기'}>{rankLabel(last)}</button>{last&&<small>{last.recorded_on.slice(5)} · 수동</small>}</td><td className={delta>0?'blog-up':delta<0?'blog-down':''}>{delta===null?'—':delta>0?'▲ '+delta:delta<0?'▼ '+Math.abs(delta):'−'}</td>{tab==='rank'?dates.map(d=><td key={d} className={d===koreaToday()?'blog-today':''}>{rankLabel(history.find(r=>r.target_id===item.id&&r.recorded_on===d))}</td>):<><td>{item.published_on>koreaToday()?'게시 예정':'게시일 등록됨'}</td><td><a href={item.url} target="_blank" rel="noopener noreferrer">열기 ↗</a></td></>}{canWrite&&<td><button onClick={()=>setEditor(item)} aria-label={item.title+' 수정'}>수정</button></td>}</tr>;})}{!rows.length&&<tr><td colSpan={tab==='rank'?days+6:8} className="blog-empty">{items.length?'검색 조건에 맞는 포스팅이 없습니다.':'등록된 포스팅이 없습니다. URL과 목표 키워드를 등록해 시작하세요.'}</td></tr>}</tbody></table></div><div className="blog-paging"><small>최근 순위는 선택 기간의 마지막 기록 · 전일 대비는 해당 기록일의 직전 날짜와 비교 · 정렬/검색은 현재 페이지 기준</small><button disabled={!page} onClick={()=>setPage(x=>x-1)}>이전</button><span>{page+1}페이지</span><button disabled={!resource.hasMore} onClick={()=>setPage(x=>x+1)}>다음</button></div></>}
 {editor&&<Editor item={editor.id?editor:null} platform={platform} onClose={()=>setEditor(null)} onSave={fields=>save(editor.id?editor:null,fields)}/>}{detail&&<Detail item={detail} history={history} canWrite={canWrite} onClose={()=>setDetail(null)} onSave={async(record,fields)=>{const token=epoch.current;const result=await source.saveBlogRank({targetId:detail.id,record,fields});if(token===epoch.current){setResource(r=>({...r,history:[...r.history.filter(x=>x.id!==result.data.id),result.data].filter(x=>x.recorded_on>=from&&x.recorded_on<=end)}));setNotice('순위 기록이 저장되었습니다.');}}}/>}
 </div>;
}
